version: 'latest'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: npstudent/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media/cats/images
  frontend:
    env_file: .env
    image: npstudent/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: npstudent/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media/cats/images
